name: 'WP POT'
description: 'Generate POT files for plugins and themes'
inputs:
  source:
    description: 'the glob to match files'
    required: false
    default: '**/*.php'
  destination:
    description: 'the destination filename'
    required: true
  text-domain:
    description: 'the text-domain of the package'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: refresh-cw
  color: blue
